### ISSUE TITLE
ExceptionsManager.js:71Warning: Native component for "RCTWKWebView" does not exist

### ISSUE THREAD

**Issue by footprint** [CRAlpha/react-native-wkwebview#30]
ExceptionsManager.js:71Warning: Native component for "RCTWKWebView" does not existreactConsoleErrorHandler @ ExceptionsManager.js:71printWarning @ warning.js:36warning @ warning.js:60requireNativeComponent @ requireNativeComponent.js:52(anonymous function) @ WKWebView.ios.js:391loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ index.js:3loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ WebViewPage.ios.js:17loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ GameCell.js:11loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ HotPage.js:10loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ HomePage.js:9loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ WelcomePage.js:13loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:123_require @ require.js:107(anonymous function) @ index.ios.js:13loadModuleImplementation @ require.js:171guardedLoadModule @ require.js:116_require @ require.js:107(anonymous function) @ require-0.js:1executeApplicationScript @ debuggerWorker.js:40(anonymous function) @ debuggerWorker.js:65

**Comment by footprint** [comment]
Resolved by Alternative #2, instead of Alternative #1

**Comment by fungilation** [comment]
No, not resolved. Help appreciated.

I'm on RN 0.37. Tried installing and linking react-native-wkwebview-reborn@0.6 and older versions, none work. App stops with similar error as this issue:

```Warning: Native component for "RCTWKWebView" does not exist```

**Comment by franverona** [comment]
I solved it by going to my Xcode project > select my target > Build Phases > Link Binary with Libraries > Add RCTWKWebView.a file and rebuild.

**Comment by colemerrick** [comment]
@fungilation I ultimately had to install rnpm and use rnpm link to resolve this issue: sudo npm install rnpm -g && rnpm link.  Alternatively, and since rnpm is included in react native core, you could run something like: npm install --save react-native-wkwebview-reborn && react-native link react-native-wkwebview-reborn

**Comment by colemerrick** [comment]
@crapthings Did you try the manual alternative in the Readme?
